### ISSUE TITLE
Replace kmeans by scikit-learn's KMeans

### ISSUE THREAD

**Issue by jacktang** [artisan1218/RBF-Network#1]
Hello,

I am going to replace kmeans function by scikit-learn's KMeans class since it supports more dimension input data. But I didn't get the same result of both kmeans, I've set the same random seed in the tests. Here is my code using  scikit-learn's KMeans:

```
def sci_kmeans(data, num_clusters):
  kms = KMeans(n_clusters=num_clusters, init='k-means++', random_state=10, tol=1e-6)
  cls_label = kms.fit(data)
  cc = kms.cluster_centers_

  labels = kms.labels_
  variances = []
  for cluster in np.unique(labels):
      cluster_samples = df[labels == cluster]  # Get samples belonging to the current cluster
      cluster_variance = np.var(cluster_samples, axis=0)  # Calculate the variance along each feature axis
      variances.append(np.mean(cluster_variance))

  return (cc, variances)
```

Could you please help me out? and why did you create your own `kmeans` function? Thanks!

**Comment by artisan1218** [comment]
Hello Jacktang,

I think replacing with scikit's KMeans is fine and you should refer to scikit's version as my own implementation might not be bug free.
